# ============================================================
# KFC Germany Halal Pilot
# Script 09: Profitability and Break-even Analysis
# ============================================================

library(tidyverse)


# ------------------------------------------------------------
# 1. LOAD PILOT BRANCHES
# ------------------------------------------------------------

pilot_branches <- read_csv(
  "outputs/pilot_branch_shortlist.csv",
  show_col_types = FALSE
)


# ------------------------------------------------------------
# 2. KFC GERMANY 2025 FACTS
# ------------------------------------------------------------

# FACT:
# KFC Germany 2025 sales = EUR 429.6 million
# KFC Germany 2025 restaurants = 217
#
# IMPORTANT:
# Sales / Umsatz is NOT profit.

kfc_sales_2025 <- 429600000
kfc_restaurants_2025 <- 217


# ------------------------------------------------------------
# 3. DERIVE AVERAGE ANNUAL SALES PER RESTAURANT
# ------------------------------------------------------------

# DERIVED:
# Simple national average.
#
# IMPORTANT:
# This is NOT actual revenue for any specific KFC branch.

avg_sales_per_restaurant <-
  kfc_sales_2025 / kfc_restaurants_2025

avg_sales_per_restaurant


# ------------------------------------------------------------
# 4. DEFINE SENSITIVITY ASSUMPTIONS
# ------------------------------------------------------------

# ASSUMPTIONS:
# These are NOT observed KFC Germany halal results.
#
# We vary them to see under what conditions
# halal conversion could become economically viable.

sales_lift_scenarios <- c(
  0.01,   # +1% sales
  0.03,   # +3%
  0.05,   # +5%
  0.10    # +10%
)

incremental_margin_scenarios <- c(
  0.30,   # 30%
  0.40,   # 40%
  0.50    # 50%
)

annual_halal_cost_scenarios <- c(
  10000,  # EUR 10k per branch per year
  25000,  # EUR 25k
  50000   # EUR 50k
)


# ------------------------------------------------------------
# 5. BUILD PER-BRANCH PROFITABILITY SCENARIOS
# ------------------------------------------------------------

profitability_scenarios <- crossing(
  sales_lift_pct = sales_lift_scenarios,
  incremental_margin = incremental_margin_scenarios,
  annual_halal_cost = annual_halal_cost_scenarios
) %>%
  mutate(
    
    # Benchmark baseline sales
    baseline_sales =
      avg_sales_per_restaurant,
    
    # Additional sales generated by halal conversion
    incremental_revenue =
      baseline_sales * sales_lift_pct,
    
    # Contribution after variable costs
    incremental_contribution =
      incremental_revenue * incremental_margin,
    
    # Net incremental profit after halal-related cost
    net_incremental_profit =
      incremental_contribution - annual_halal_cost,
    
    # Simple profitability indicator
    profitable =
      net_incremental_profit > 0
  )


# Inspect scenario table
profitability_scenarios


# ------------------------------------------------------------
# 6. CALCULATE BREAK-EVEN SALES LIFT
# ------------------------------------------------------------

break_even <- crossing(
  incremental_margin = incremental_margin_scenarios,
  annual_halal_cost = annual_halal_cost_scenarios
) %>%
  mutate(
    
    baseline_sales =
      avg_sales_per_restaurant,
    
    # Extra revenue required to cover halal cost
    break_even_incremental_revenue =
      annual_halal_cost / incremental_margin,
    
    # Required percentage increase in annual sales
    break_even_sales_lift_pct =
      100 *
      break_even_incremental_revenue /
      baseline_sales
  )


# Show break-even table
break_even %>%
  arrange(
    annual_halal_cost,
    incremental_margin
  )


# ------------------------------------------------------------
# 7. APPLY ALL SCENARIOS TO 8 PILOT BRANCHES
# ------------------------------------------------------------

pilot_profitability <- pilot_branches %>%
  select(
    store_id,
    city,
    address,
    comparison_share_pct,
    evidence_strength
  ) %>%
  crossing(
    profitability_scenarios
  )


# Check number of branches
n_distinct(pilot_profitability$store_id)


# ------------------------------------------------------------
# 8. AGGREGATE RESULTS FOR FULL 8-BRANCH PILOT
# ------------------------------------------------------------

pilot_total_scenarios <- pilot_profitability %>%
  group_by(
    sales_lift_pct,
    incremental_margin,
    annual_halal_cost
  ) %>%
  summarise(
    
    branches =
      n_distinct(store_id),
    
    # Total additional sales across all 8 branches
    incremental_revenue =
      sum(incremental_revenue),
    
    # Total contribution from additional sales
    incremental_contribution =
      sum(incremental_contribution),
    
    # Total annual halal cost across pilot
    total_halal_cost =
      sum(annual_halal_cost),
    
    # Total net incremental profit
    net_incremental_profit =
      sum(net_incremental_profit),
    
    .groups = "drop"
  )


# Inspect all pilot scenarios
pilot_total_scenarios %>%
  arrange(
    annual_halal_cost,
    incremental_margin,
    sales_lift_pct
  )


# ------------------------------------------------------------
# 9. BASELINE SENSITIVITY CASE
# ------------------------------------------------------------

# This is ONLY an illustrative scenario:
#
# annual halal cost = EUR 25,000 per branch
# incremental contribution margin = 40%
#
# These are assumptions, not observed facts.

baseline_sensitivity <- pilot_total_scenarios %>%
  filter(
    annual_halal_cost == 25000,
    incremental_margin == 0.40
  ) %>%
  arrange(
    sales_lift_pct
  )


baseline_sensitivity


# ------------------------------------------------------------
# 10. FORMAT BASELINE CASE FOR EASY INTERPRETATION
# ------------------------------------------------------------

baseline_sensitivity_readable <- baseline_sensitivity %>%
  mutate(
    
    sales_lift_percent =
      100 * sales_lift_pct,
    
    incremental_revenue =
      round(incremental_revenue, 0),
    
    incremental_contribution =
      round(incremental_contribution, 0),
    
    total_halal_cost =
      round(total_halal_cost, 0),
    
    net_incremental_profit =
      round(net_incremental_profit, 0)
  ) %>%
  select(
    sales_lift_percent,
    branches,
    incremental_revenue,
    incremental_contribution,
    total_halal_cost,
    net_incremental_profit
  )


baseline_sensitivity_readable


# ------------------------------------------------------------
# 11. BASIC SANITY CHECKS
# ------------------------------------------------------------

# Expected: 8 unique pilot branches
n_distinct(pilot_branches$store_id)

# Expected: 36 profitability combinations
nrow(profitability_scenarios)

# Expected: 9 break-even combinations
nrow(break_even)

# Expected: 36 aggregate pilot scenarios
nrow(pilot_total_scenarios)

# Expected: 4 baseline scenarios
nrow(baseline_sensitivity)


# ------------------------------------------------------------
# 12. SAVE OUTPUTS
# ------------------------------------------------------------

write_csv(
  profitability_scenarios,
  "outputs/profitability_sensitivity_per_branch.csv"
)

write_csv(
  break_even,
  "outputs/break_even_sales_lift.csv"
)

write_csv(
  pilot_total_scenarios,
  "outputs/pilot_profitability_sensitivity.csv"
)

write_csv(
  baseline_sensitivity_readable,
  "outputs/baseline_profitability_sensitivity.csv"
)





baseline_sensitivity_readable


nrow(profitability_scenarios)
nrow(break_even)
nrow(pilot_total_scenarios)
